"""SPICE-enhanced EMC analysis — PDN impedance and EMI filter simulations.

Optional module that uses the SPICE skill's simulator infrastructure to
provide more accurate PDN impedance sweeps and EMI filter insertion loss
measurements. Falls back gracefully when no simulator is available.

Requires: ngspice, LTspice, or Xyce (auto-detected).
Zero required external Python dependencies.
"""

import math
import os
import sys
import tempfile

# Add spice skill scripts to path for simulator imports
_SPICE_SCRIPTS = os.path.join(os.path.dirname(__file__), '..', '..', 'spice', 'scripts')
if os.path.isdir(_SPICE_SCRIPTS):
    sys.path.insert(0, os.path.abspath(_SPICE_SCRIPTS))


def detect_spice_simulator():
    """Try to detect a SPICE simulator.

    Returns a SimulatorBackend instance or None.
    """
    try:
        from spice_simulator import detect_simulator
        return detect_simulator()
    except ImportError:
        return None


def _format_eng(value):
    """Format a value in SPICE engineering notation."""
    if value == 0:
        return "0"
    abs_val = abs(value)
    prefixes = [
        (1e12, 'T'), (1e9, 'G'), (1e6, 'Meg'), (1e3, 'k'),
        (1, ''), (1e-3, 'm'), (1e-6, 'u'), (1e-9, 'n'), (1e-12, 'p'),
        (1e-15, 'f'),
    ]
    for threshold, prefix in prefixes:
        if abs_val >= threshold * 0.999:
            scaled = value / threshold
            if scaled == int(scaled):
                return f"{int(scaled)}{prefix}"
            return f"{scaled:.4g}{prefix}"
    return f"{value:.6e}"


# ---------------------------------------------------------------------------
# PDN Impedance SPICE Testbench
# ---------------------------------------------------------------------------

def generate_pdn_netlist(caps, plane_cap_f=0):
    """Generate a SPICE netlist for PDN impedance measurement.

    Each cap is modeled as series ESR-ESL-C from the rail node to ground.
    A 1A AC current source drives the rail — V(rail) = Z(f) directly.

    Args:
        caps: List of dicts with farads, esr_ohm, esl_h, and optionally ref.
        plane_cap_f: Interplane capacitance in Farads (added as parallel C).

    Returns:
        SPICE netlist string (without analysis/measurement commands).
    """
    lines = []
    lines.append('* PDN Impedance Sweep — auto-generated by kicad-happy EMC')
    lines.append(f'* {len(caps)} decoupling cap(s) in parallel, series R-L-C model')
    lines.append('')

    for i, cap in enumerate(caps):
        ref = cap.get('ref', f'C{i+1}')
        farads = cap.get('farads', 0)
        esr = cap.get('esr_ohm', 0.1)
        esl = cap.get('esl_h', 1e-9)
        if farads <= 0:
            continue

        n1 = f'n_esr_{i}'
        n2 = f'n_esl_{i}'
        lines.append(f'* {ref}: {_format_eng(farads)}F, ESR={_format_eng(esr)}, ESL={_format_eng(esl)}H')
        lines.append(f'R_esr_{i} rail {n1} {_format_eng(esr)}')
        lines.append(f'L_esl_{i} {n1} {n2} {_format_eng(esl)}')
        lines.append(f'C_cap_{i} {n2} 0 {_format_eng(farads)}')

    if plane_cap_f > 0:
        lines.append(f'')
        lines.append(f'* Interplane capacitance')
        lines.append(f'C_plane rail 0 {_format_eng(plane_cap_f)}')

    lines.append('')
    lines.append('* Bias resistor (prevents floating node)')
    lines.append('R_bias rail 0 1Meg')
    lines.append('')
    lines.append('* 1A AC current source — V(rail) = Z(f)')
    lines.append('IAC 0 rail DC 0 AC 1')

    return '\n'.join(lines)


def run_pdn_spice(caps, plane_cap_f=0, backend=None,
                  freq_start=1e3, freq_stop=1e9,
                  points_per_decade=50, timeout=10):
    """Run SPICE AC sweep for PDN impedance and return results.

    Args:
        caps: List of cap dicts (farads, esr_ohm, esl_h).
        plane_cap_f: Interplane capacitance in Farads.
        backend: SimulatorBackend instance.
        freq_start/freq_stop: Sweep range in Hz.
        points_per_decade: Resolution.
        timeout: Simulation timeout in seconds.

    Returns:
        (success, sweep) where sweep is a list of {freq_hz, impedance_ohm}
        compatible with find_anti_resonances(). Returns (False, None) on failure.
    """
    if backend is None:
        return False, None

    netlist = generate_pdn_netlist(caps, plane_cap_f)

    # Build ngspice control block to output impedance at sampled frequencies
    # We use wrdata to dump the full AC sweep, then parse it
    try:
        from spice_simulator import NgspiceBackend, LtspiceBackend, XyceBackend
        from spice_templates import SpiceTestbench
    except ImportError:
        return False, None

    # Use SpiceTestbench for portable rendering
    decades = math.log10(freq_stop / freq_start)
    ppd = int(points_per_decade)
    ac_spec = f'dec {ppd} {_format_eng(freq_start)} {_format_eng(freq_stop)}'

    # Measurements: impedance at key frequencies + min/max
    measurements = [
        ('z_min', 'min', 'vm(rail)'),
        ('f_at_zmin', 'when', 'vm(rail)', 'z_min'),
    ]

    # Add measurement points at logarithmic intervals for the sweep
    # Use specific frequency probes
    probe_freqs = []
    n_probes = int(decades * 10)  # 10 probes per decade
    for i in range(n_probes + 1):
        f = freq_start * (10 ** (i * decades / n_probes))
        probe_freqs.append(f)
        meas_name = f'z_f{i}'
        measurements.append((meas_name, 'find', 'vm(rail)', f'at={_format_eng(f)}'))

    tb = SpiceTestbench(netlist, [('ac', ac_spec)], measurements)

    workdir = tempfile.mkdtemp(prefix='emc_pdn_')
    cir_file = os.path.join(workdir, 'pdn.cir')
    out_file = os.path.join(workdir, 'pdn_results.txt')

    try:
        cir_content = tb.render(backend, out_file)
        with open(cir_file, 'w') as f:
            f.write(cir_content)

        success, stdout, stderr = backend.run(cir_file, timeout=timeout)
        if not success:
            return False, None

        results = backend.parse_results(out_file, stdout, stderr)
        if not results:
            return False, None

        # Build impedance sweep from probe measurements
        sweep = []
        for i, freq in enumerate(probe_freqs):
            z_key = f'z_f{i}'
            z_val = results.get(z_key)
            if z_val is not None and isinstance(z_val, (int, float)) and z_val > 0:
                sweep.append({'freq_hz': freq, 'impedance_ohm': z_val})

        if len(sweep) < 5:
            return False, None

        return True, sweep

    except Exception:
        return False, None
    finally:
        # Cleanup
        import shutil
        try:
            shutil.rmtree(workdir, ignore_errors=True)
        except Exception:
            pass


# ---------------------------------------------------------------------------
# EMI Filter Insertion Loss SPICE Testbench
# ---------------------------------------------------------------------------

def generate_filter_netlist(inductor_h, cap_f, esr=0.1, esl=1e-9,
                            source_z=50, load_z=50):
    """Generate a SPICE netlist for EMI filter insertion loss.

    Models a simple L-C low-pass filter between source and load impedances.
    Measures Vout/Vin = insertion loss.

    Args:
        inductor_h: Filter inductor value in Henries.
        cap_f: Filter capacitor value in Farads.
        esr: Capacitor ESR in Ohms.
        esl: Capacitor ESL in Henries.
        source_z: Source impedance in Ohms.
        load_z: Load impedance in Ohms.

    Returns:
        SPICE netlist string.
    """
    lines = []
    lines.append('* EMI Filter Insertion Loss — auto-generated by kicad-happy EMC')
    lines.append(f'* L={_format_eng(inductor_h)}H, C={_format_eng(cap_f)}F')
    lines.append(f'* Source Z={source_z}R, Load Z={load_z}R')
    lines.append('')
    lines.append('V1 in 0 AC 1')
    lines.append(f'R_source in n1 {_format_eng(source_z)}')
    lines.append(f'L_filter n1 n2 {_format_eng(inductor_h)}')
    lines.append(f'R_cap_esr n2 n3 {_format_eng(esr)}')
    lines.append(f'L_cap_esl n3 n4 {_format_eng(esl)}')
    lines.append(f'C_filter n4 0 {_format_eng(cap_f)}')
    lines.append(f'R_load n2 0 {_format_eng(load_z)}')

    return '\n'.join(lines)


def run_filter_spice(inductor_h, cap_f, switching_freq_hz,
                     esr=0.1, esl=1e-9, backend=None, timeout=10):
    """Run SPICE AC sweep for EMI filter and measure insertion loss.

    Args:
        inductor_h: Filter inductor in Henries.
        cap_f: Filter capacitor in Farads.
        switching_freq_hz: Frequency at which to measure insertion loss.
        esr/esl: Cap parasitics.
        backend: SimulatorBackend instance.
        timeout: Simulation timeout.

    Returns:
        (success, results_dict) where results_dict has:
          il_at_fsw_db: Insertion loss at switching frequency (negative = attenuation)
          il_at_3fsw_db: Insertion loss at 3rd harmonic
          cutoff_hz: -3dB frequency
        Returns (False, None) on failure.
    """
    if backend is None:
        return False, None

    netlist = generate_filter_netlist(inductor_h, cap_f, esr, esl)

    try:
        from spice_templates import SpiceTestbench
    except ImportError:
        return False, None

    # Sweep from 100 Hz to 10× switching frequency
    f_stop = max(switching_freq_hz * 10, 100e6)
    ac_spec = f'dec 100 100 {_format_eng(f_stop)}'

    measurements = [
        ('il_at_fsw', 'find', 'vdb(n2)', f'at={_format_eng(switching_freq_hz)}'),
        ('il_at_3fsw', 'find', 'vdb(n2)', f'at={_format_eng(switching_freq_hz * 3)}'),
        ('fc_3db', 'when', 'vdb(n2)', '-3'),
    ]

    tb = SpiceTestbench(netlist, [('ac', ac_spec)], measurements)

    workdir = tempfile.mkdtemp(prefix='emc_filter_')
    cir_file = os.path.join(workdir, 'filter.cir')
    out_file = os.path.join(workdir, 'filter_results.txt')

    try:
        cir_content = tb.render(backend, out_file)
        with open(cir_file, 'w') as f:
            f.write(cir_content)

        success, stdout, stderr = backend.run(cir_file, timeout=timeout)
        if not success:
            return False, None

        results = backend.parse_results(out_file, stdout, stderr)
        if not results:
            return False, None

        return True, {
            'il_at_fsw_db': results.get('il_at_fsw', 0),
            'il_at_3fsw_db': results.get('il_at_3fsw', 0),
            'cutoff_hz': results.get('fc_3db', 0),
        }

    except Exception:
        return False, None
    finally:
        import shutil
        try:
            shutil.rmtree(workdir, ignore_errors=True)
        except Exception:
            pass
