M48
; DRILL file KiCad 10.0.1-10.0.1~ubuntu24.04.1 date 2026-04-18T12:41:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-18T12:41:44-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1-10.0.1~ubuntu24.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X148.0Y-100.0
T2
X130.0Y-100.0
X130.0Y-102.54
M30
